export type ChangelogEntry = {
  version: string;
  date: string;
  title: string;
  description: string;
  type: 'feature' | 'improvement' | 'fix' | 'milestone';
  highlights: string[];
};

// Add new entries at the TOP of this array (newest first)
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '4.2.0',
    date: '2026-02-20',
    title: 'Smart Preview, Context-Aware Coach & Apple-Ready Polish',
    description: 'The Coach now feels alive before you type a word. Smart Preview remembers your last conversation, chips adapt to time of day and context, the input bar rotates smart suggestions, and the entire layout got an Apple-level polish pass.',
    type: 'feature',
    highlights: [
      'Smart Preview on load — if you have saved threads, Coach shows a ghosted card: "Last convo with [name] — Tap to pick up where you left off." If no history, rotates time-of-day scenarios (Friday night dead chat? Monday morning reply?)',
      'Context-Aware Chips — scenario buttons now have dynamic subtitles that change based on your threads, time of day, and day of week. Relevant chips glow violet.',
      'Dynamic placeholder rotation — input cycles through smart examples every 4 seconds: "Decode why she sent \'k.\'...", "Am I overthinking this text?", etc.',
      'Send button morph — empty input shows Send icon, typing morphs it to ✨ Go with sparkle',
      'Personalized Coach header — your first initial as a gradient avatar, dynamic greeting: "What\'s up [Name]?"',
      'Apple iMessage layout — Coach card restructured as flex column with sticky input, scrollable chat/chips, proper maxHeight so input never gets cut off',
      'Chips now in a 2-column grid for compact mobile display instead of stacking vertically',
      'iOS safe area padding — input no longer hidden behind the home indicator on iPhone',
      'Fixed "Paste what they said" empty state leaking into Coach mode',
      'Shortened placeholder text to prevent truncation on narrow screens',
    ],
  },
  {
    version: '4.1.0',
    date: '2026-02-19',
    title: 'Unified History + Coach-Only UI',
    description: 'Coach is now the only interface — no tabs, no modes. All your sessions auto-save and appear in a unified History page. Resume any conversation with one tap.',
    type: 'feature',
    highlights: [
      'Coach-only UI — removed all tabs (Reply, Decode, Opener, Revive). Scenario chips handle everything.',
      'Auto-save coach sessions — every coach conversation is saved to your history automatically',
      'Unified History page (/history) — search, filter by Coach/Thread/Replies, tap to resume any session',
      'Deep-link from History — tap any session to jump back into the conversation in /app',
      'Dashboard updated — "Recent Wins" replaced with unified History showing threads + coach sessions',
      'Profile page — History section now shows all saved sessions alongside quick reply history',
      'Duplicate scenario chips removed from app page for cleaner UI',
      'Homepage redesigned — new hero, social proof bar, stronger CTAs, Coach-first messaging',
    ],
  },
  {
    version: '4.0.0',
    date: '2026-02-19',
    title: 'V4 — Coach Mode: Your AI Texting Coach',
    description: 'The biggest redesign yet. Coach Mode is now the face of Text Wingman — a conversational AI coach that reads your situation, gives strategy, generates replies, decodes messages, writes openers, and revives dead threads. All from one chat interface.',
    type: 'milestone',
    highlights: [
      'Coach Mode — conversational AI texting coach as the primary interface. Ask anything: "read this convo", "what should I say?", "decode this", "write me an opener", "revive this dead chat"',
      'Reply cards inline — Coach suggests 3 replies (Quick, Spicy, Soft) with one-tap USE to send to your thread',
      'Strategy badges — momentum, balance, and energy analysis shown inline on every Coach response',
      'Intel Sidebar (desktop) — real-time health ring, risk score, timing window, strategy card, context & goal selectors',
      'Mobile Intel Sheet — expandable panel showing health, risk, timing, strategy, and selectors on mobile',
      'Screenshot multi-upload — upload multiple screenshots at once in Coach mode for full context',
      'Suggestion chips — empty state shows quick-start options: Read convo, What should I say, Decode, Opener, Revive',
      'Thread Mode preserved as secondary view — toggle COACH/THREAD in header',
      'Inline decode — hover any "them" message in thread to decode it instantly',
      'Simulated outcomes — % confidence score on each reply with BEST badge',
      'Edit + Polish preserved — tap Edit on any reply, add your ideas, hit Polish',
      'Regenerate button — REFRESH for fresh reply options without re-entering anything',
      'Dark glass UI throughout — Glass component with neon glow options, animated gradient background',
      'Paywall redesigned in dark glass to match the rest of the app',
      'Removed tab bar (Reply/Decode/Opener/Revive) — Coach handles all modes naturally',
      'Removed standalone Strategy Chat — Coach IS the strategy chat now',
      'Page size reduced from ~3,600 lines to ~1,100 lines',
    ],
  },
  {
    version: '3.7.0',
    date: '2026-02-19',
    title: 'Deep AI Upgrade — Sarcasm Detection, Power Dynamics & Style Matching',
    description: 'Every AI agent in the pipeline got a major brain upgrade. The system now detects sarcasm vs low investment, kidding vs serious, power dynamics, and matches your personal texting style from your reply history.',
    type: 'milestone',
    highlights: [
      'Sarcasm detection — StrategyAgent now distinguishes playful sarcasm ("wateveerr", "suuure") from genuine low investment, and flags it for DraftAgent to mirror correctly',
      'Kidding vs serious — AI detects when they\'re joking ("i hate you lol") vs actually upset ("i hate this") and replies match the real tone',
      'Power dynamics — StrategyAgent now tracks who\'s investing more, who initiates, who asks more questions, and flags "User chasing" when the balance is off',
      'Energy level classification — conversations now get a vibe label: High flirt, Playful, Warm, Polite, Dry, or Cold — shapes every reply',
      'Risk flags — StrategyAgent surfaces specific signals (frame testing, over-investing, sarcasm likely playful) so DraftAgent knows what to watch for',
      'Personal style matching — DraftAgent now fetches your last 8 replies and uses them as style examples so replies sound more like you',
      'Vibe Check upgraded — now scores confidence level, neediness risk, sarcasm risk, and frame strength on top of energy and vibe',
      'DecodeAgent upgraded — now explicitly detects sarcasm, kidding, low investment, and power dynamics in messages you paste',
      'Strategy alignment — RuleCheckAgent and ToneVerifyAgent now receive strategy context and check that replies match the recommended move',
      'Core principles added to all agents — never needy, assume positive intent, distinguish sarcasm from low investment, respect power balance',
    ],
  },
  {
    version: '3.6.0',
    date: '2026-02-18',
    title: 'Screenshot Auto-Thread & Rename',
    description: 'Upload a screenshot and your full conversation instantly appears in the thread with replies ready — no extra steps. Plus inline thread renaming so you can name threads anything you want.',
    type: 'improvement',
    highlights: [
      'Screenshot auto-thread — uploading a screenshot now instantly populates the thread with all extracted messages and shows replies, no "Continue in Thread" button needed',
      'Thread auto-saves immediately after screenshot load — pick up where you left off anytime',
      'Inline thread rename — tap the purple thread name to rename it (e.g. "spa girl", "dating app match") and it saves instantly',
      'Screenshot extraction upgraded to gpt-4o with high-detail mode — captures every message in the screenshot including ones near the top, with correct sender sides',
      'Fixed sender swap bug — messages you sent (right/blue) now correctly show as "You", not "Them"',
    ],
  },
  {
    version: '3.5.0',
    date: '2026-02-17',
    title: 'Subtext Intelligence & Quality Fixes',
    description: 'The AI now reads between the lines — playful dismissals, coy teasing, sarcasm, and stretched words are interpreted correctly instead of literally. Plus reply card fixes and delete thread feedback.',
    type: 'feature',
    highlights: [
      'Subtext Intelligence — AI now reads between the lines: "wateveerr" = playful, "heyyyy" = excited, "suuure" = banter, not literal dismissals',
      'Works across V1 and V2 — both prompt pipelines upgraded with emotional intelligence for coy, sarcastic, and teasing messages',
      'V1/V2 badge fix — reply cards now correctly show "v1" (purple) or "v2" (green) based on your actual toggle, not just Pro status',
      'Delete thread feedback — red trash button now shows a toast confirmation on success and error on failure',
      'Tone ✓ badge correctly hidden when using V1 mode',
    ],
  },
  {
    version: '3.4.0',
    date: '2026-02-16',
    title: 'Vibe Check & Tone Translator',
    description: 'Two new AI tools: get real-time feedback on your draft before you send it, and instantly rewrite any message in a different energy.',
    type: 'feature',
    highlights: [
      'Vibe Check — as you type, AI analyzes your draft and shows energy level (🟢🟡🔴), a vibe label, score out of 10, and a one-line coaching tip',
      'Tone Translator — wrote your own message? Tap "Rewrite in a different tone" and pick Flirty, Chill, Bold, Witty, Warm, or Pro to instantly transform it',
      'Vibe Check auto-runs 1.5s after you stop typing (8+ characters) — no button needed',
      'Tone Translator preserves your intent and details while changing the energy',
    ],
  },
  {
    version: '3.3.2',
    date: '2026-02-16',
    title: 'V1/V2 Mode Toggle for Pro',
    description: 'Pro users can now switch between V2 Verified (strategy + 3-agent pipeline) and V1 Fast Mode for quicker replies when you just need something fast.',
    type: 'improvement',
    highlights: [
      'V1/V2 toggle — tap the mode badge to switch between V2 Verified and V1 Fast Mode',
      'V2 (default) — full strategy analysis, 3-agent pipeline, ≤18 words enforced, tone-verified',
      'V1 Fast Mode — quick single-call replies with no strategy overhead, ~2x faster',
      'Top status badge updates to reflect your current mode',
    ],
  },
  {
    version: '3.3.1',
    date: '2026-02-16',
    title: 'Custom Context, Smart Thread Update & Speed Boost',
    description: 'Tell the AI about your situation in your own words, update threads by just uploading a new screenshot, and enjoy noticeably faster screenshot processing.',
    type: 'feature',
    highlights: [
      'Custom Context — free-text field to describe your situation (e.g. "talking 2 weeks, she\'s a nurse, went on one date") passed to all AI endpoints',
      'Smart Thread Update — upload a new screenshot when you already have a thread and only new messages get added automatically',
      'Screenshot speed boost — switched to gpt-4o-mini for extraction, smaller image compression, ~2-3x faster uploads',
      'Custom context works across Reply, Revive, Decode, Opener, and Screenshot Briefing modes',
    ],
  },
  {
    version: '3.3.0',
    date: '2026-02-16',
    title: 'Edit + Polish, Regenerate & Smarter Context',
    description: 'Edit any reply inline, add your own ideas, and let AI polish it smooth. Regenerate replies when you want fresh options. Plus a major upgrade to how the AI reads conversation context.',
    type: 'feature',
    highlights: [
      'Edit + Polish — tap Edit on any reply, add your own ideas (like "let\'s grab food"), then hit Polish to have AI smooth it out while keeping your additions',
      'Regenerate Replies — "Generate different replies" button for fresh options without re-entering the conversation',
      'Smarter Context Analysis — AI now detects re-initiation (they came back to you), personal sharing, questions, and growing energy instead of misreading casual style as low effort',
      'Content Engagement — replies now reference specifics from their message instead of giving generic responses',
      'Thread input fix — "Add as their message" and "Add as my message" buttons always visible after deleting a thread message',
      'Use As Is option — save your raw edit without AI polish if you prefer your own wording',
    ],
  },
  {
    version: '3.2.0',
    date: '2026-02-15',
    title: 'Revive Mode, Screenshot Briefing & Energy Matching',
    description: 'New Revive mode for dead conversations, instant Screenshot Briefing with strategy coaching, smarter energy-matching replies, and expanded platform support.',
    type: 'feature',
    highlights: [
      'Revive Mode — re-engage dead/stale conversations with 3 strategic messages (smooth, bold, warm) plus AI analysis of why the convo died',
      'Screenshot Briefing — upload a screenshot in Reply mode and get instant strategy coaching + 3 replies without typing anything',
      'Energy Matching — replies now match the other person\'s effort level. Short messages get short replies, slang gets slang back',
      'Facebook Dating & Messenger support — screenshot extraction now recognizes FB Dating, Messenger, and Snapchat',
      'Screenshot upload in Opener mode — upload a profile screenshot for context before generating openers',
      'Low-effort detection — Strategy Mode now flags stalling conversations and auto-applies no-questions + keep-short constraints',
    ],
  },
  {
    version: '3.0.0',
    date: '2026-02-15',
    title: 'V3 — Conversational Intelligence',
    description: 'The biggest update yet. Text Wingman is no longer just a reply generator — it\'s a full conversational AI companion with strategy coaching.',
    type: 'milestone',
    highlights: [
      'Thread Mode — full back-and-forth conversation loop with "I sent this" and custom replies',
      'StrategyAgent — AI coaching card showing momentum, balance, and recommended move (Pro)',
      'Thread-Aware AI — every reply is generated with full conversation context, not just the last message',
      'Dark glass UI overhaul — adopted across dashboard and app page for a modern, premium feel',
      'Double-text support — add multiple messages from either side without forced alternation',
      'Auto-save threads — conversations sync in the background after 2+ messages',
    ],
  },
  {
    version: '2.5.0',
    date: '2026-02-13',
    title: 'Message Decoder, Opening Lines, Coach Tips & Saved Threads',
    description: 'Four new features: decode what they really mean, generate opening lines, get coaching tips, and save conversation threads.',
    type: 'feature',
    highlights: [
      '"What Do They Mean?" Decoder — analyzes subtext, intent, energy, and red/green flags',
      'Opening Line Generator — first-message mode for dating apps, Instagram DMs, cold texts & more',
      'Coach Tips — tactical advice on how to respond based on conversation dynamics',
      'Saved Threads — name and save conversations, come back for context-aware replies',
    ],
  },
  {
    version: '2.4.0',
    date: '2026-02-12',
    title: 'Screenshot Upload — Full Conversation Extraction',
    description: 'Upload a screenshot of any conversation and our AI reads the entire thread. No more copy-pasting between apps.',
    type: 'feature',
    highlights: [
      'Upload screenshots from iMessage, WhatsApp, Instagram, Tinder & more',
      'AI extracts the full conversation thread with Them/You labels',
      'Detects who said what and identifies the last received message',
      'One-tap from screenshot to generated replies',
    ],
  },
  {
    version: '2.3.1',
    date: '2026-02-12',
    title: 'Mobile UX Overhaul',
    description: 'Major responsiveness pass across every page — optimized for thumb-friendly mobile use.',
    type: 'improvement',
    highlights: [
      'Context grid now 2 columns on small screens',
      'Removed janky hover effects on reply cards for touch devices',
      'Banners stack properly on mobile',
      'Safe bottom padding on all pages',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-02-11',
    title: 'Homepage Refresh',
    description: 'Cleaned up the homepage with honest copy, dynamic copyright, and removed placeholder content.',
    type: 'improvement',
    highlights: [
      'Removed placeholder testimonials',
      'Fixed pricing card contradictions',
      'Dynamic copyright year',
      'New "Screenshot It. We\'ll Read It." feature showcase section',
    ],
  },
  {
    version: '2.2.0',
    date: '2026-02-10',
    title: 'Dashboard Glow-Up',
    description: 'Redesigned dashboard with better stats, recent wins, and a cleaner layout.',
    type: 'improvement',
    highlights: [
      'Total Replies stat card',
      'Recent Wins section with quick view',
      'Renewal CTA near subscription countdown',
      'Compact quick-action CTA',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-02-05',
    title: 'Security Hardening & Admin Dashboard',
    description: 'Deep security audit plus a full admin panel for managing users, billing, and experiments.',
    type: 'milestone',
    highlights: [
      'Fixed critical RLS policies on entitlements table',
      'Server-side auth on all API routes',
      'Full admin dashboard with 7 sections',
      'Feature flags system for gradual rollouts',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-01-20',
    title: 'V2 Launch — 3-Agent Verified Replies',
    description: 'The biggest update yet. Every reply now goes through a 3-agent pipeline: Draft → Rule-Check → Tone-Verify.',
    type: 'milestone',
    highlights: [
      '3-agent pipeline: Draft, Rule-Check, Tone-Verify',
      '≤18 words enforced, no emojis, no needy text',
      'Auto-revise up to 2x before showing results',
      'Confidence scoring on every reply',
    ],
  },
  {
    version: '1.0.0',
    date: '2025-12-01',
    title: 'Text Wingman Launch',
    description: 'The original release. Paste a message, pick a tone, get 3 reply options.',
    type: 'milestone',
    highlights: [
      '3 tone options: Shorter, Spicier, Softer',
      'Context selector for Dating, Friends, Work',
      'Copy to clipboard with one tap',
      'Free tier with daily limits',
    ],
  },
];

export const CURRENT_VERSION = CHANGELOG[0].version;
export const LATEST_UPDATE = CHANGELOG[0];

export const TYPE_CONFIG = {
  feature: { emoji: '🚀', label: 'New Feature', color: 'text-green-400', bg: 'bg-green-500/20', border: 'border-green-500/30' },
  improvement: { emoji: '✨', label: 'Improvement', color: 'text-blue-400', bg: 'bg-blue-500/20', border: 'border-blue-500/30' },
  fix: { emoji: '🔧', label: 'Bug Fix', color: 'text-orange-400', bg: 'bg-orange-500/20', border: 'border-orange-500/30' },
  milestone: { emoji: '🏆', label: 'Milestone', color: 'text-purple-400', bg: 'bg-purple-500/20', border: 'border-purple-500/30' },
};
