export type SeoGuide = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  heroEmoji: string;
  situation: string;
  theirMessage: string;
  badReply: string;
  badWhy: string;
  goodReplies: { tone: string; text: string; why: string }[];
  tips: string[];
  keywords: string[];
};

export const SEO_GUIDES: SeoGuide[] = [
  {
    slug: 'wyd-text',
    title: 'How to Reply to "wyd" Texts',
    metaTitle: 'How to Reply to "wyd" — Best Responses for Every Situation',
    metaDescription: 'Don\'t just say "nothing much." Here are the best replies to "wyd" texts that keep the conversation going — whether it\'s a crush, friend, or someone new.',
    heroEmoji: '📱',
    situation: 'They hit you with the classic "wyd" — the most common text opener. Your response sets the tone for the entire conversation.',
    theirMessage: 'wyd',
    badReply: 'nothing much hbu',
    badWhy: 'Boring. Kills momentum. Puts all the effort on them. Zero personality.',
    goodReplies: [
      { tone: 'Flirty', text: 'thinking about getting into trouble. you offering?', why: 'Playful, creates intrigue, opens the door for plans.' },
      { tone: 'Chill', text: 'just vibing. what\'s good with you', why: 'Relaxed but reciprocates energy. Shows you\'re unbothered.' },
      { tone: 'Bold', text: 'come find out', why: 'Confident, short, creates tension. Works great with a crush.' },
    ],
    tips: [
      'Never mirror their low effort — add at least one interesting detail',
      'If you\'re into them, hint at plans without directly asking',
      '"wyd" is an invitation to be interesting, not a survey question',
      'Keep it under 10 words. Long replies to "wyd" look try-hard',
    ],
    keywords: ['how to reply to wyd', 'what to say when someone texts wyd', 'wyd response', 'best reply to wyd text'],
  },
  {
    slug: 'left-on-read',
    title: 'What to Do When Left on Read',
    metaTitle: 'Left on Read? Here\'s Exactly What to Do (Don\'t Panic)',
    metaDescription: 'Got left on read? Don\'t double text with desperation. Here\'s what to send after being left on read — from the bold move to the smooth recovery.',
    heroEmoji: '👻',
    situation: 'You sent a message, they saw it, and... nothing. It\'s been hours (or days). The worst feeling in texting.',
    theirMessage: '(read ✓✓ — no reply)',
    badReply: 'hello?? did you get my message? are you okay?',
    badWhy: 'Needy, desperate, puts pressure on them. Makes you look insecure.',
    goodReplies: [
      { tone: 'Smooth', text: 'anyway i found that spot you\'d love', why: 'Ignores the gap naturally. Creates curiosity. No pressure.' },
      { tone: 'Bold', text: 'your loss, i had a great story to tell', why: 'Playfully calls it out without being bitter. Confident energy.' },
      { tone: 'Warm', text: 'hope your week\'s going well', why: 'Genuine, zero pressure, keeps the door open without chasing.' },
    ],
    tips: [
      'Wait at least 24-48 hours before sending anything',
      'Never acknowledge the gap — act like it didn\'t happen',
      'Your follow-up should add value, not ask "why didn\'t you reply"',
      'If it happens repeatedly, they\'re not interested. Move on.',
      'One follow-up is fine. Two is the limit. Three is desperate.',
    ],
    keywords: ['left on read', 'what to do when left on read', 'how to respond after being left on read', 'left on read what to text'],
  },
  {
    slug: 'dry-texter',
    title: 'How to Deal with Dry Texters',
    metaTitle: 'Talking to a Dry Texter? Here\'s How to Get More Than "lol" Back',
    metaDescription: 'Tired of one-word replies? Learn how to text a dry texter and either spark real conversation or know when to walk away.',
    heroEmoji: '🏜️',
    situation: 'Every reply from them is "lol", "yeah", "nice", or "haha". You\'re carrying the entire conversation.',
    theirMessage: 'lol yeah',
    badReply: 'so what else is going on? how was your day? did you do anything fun?',
    badWhy: 'Bombarding with questions when they\'re giving nothing. You\'re chasing.',
    goodReplies: [
      { tone: 'Mirror', text: 'lol', why: 'Match their energy. If they care, they\'ll step up. If not, you saved your dignity.' },
      { tone: 'Pivot', text: 'you\'re coming to [place] saturday btw', why: 'Skip texting, go straight to plans. Some people are just bad texters but great in person.' },
      { tone: 'Direct', text: 'you\'re a terrible texter and i respect it', why: 'Calls it out with humor. Breaks the pattern without being confrontational.' },
    ],
    tips: [
      'Stop asking questions — make statements instead',
      'Some people text dry but are interested. Suggest meeting up to find out.',
      'Match their energy for 2-3 messages. If they don\'t escalate, they\'re not interested.',
      'Never write paragraphs to someone giving you one word.',
    ],
    keywords: ['dry texter', 'how to talk to a dry texter', 'one word replies', 'she only texts lol'],
  },
  {
    slug: 'ex-texted-back',
    title: 'Your Ex Texted — Here\'s What to Say',
    metaTitle: 'Your Ex Texted You? Here\'s Exactly How to Respond',
    metaDescription: 'Your ex just reached out. Don\'t panic, don\'t over-think it. Here\'s how to respond whether you want them back or want to stay gone.',
    heroEmoji: '💔',
    situation: 'Out of nowhere, your ex texts. Maybe it\'s "hey", maybe it\'s "I miss you", maybe it\'s 1am. Either way — your response matters.',
    theirMessage: 'hey, been thinking about you lately',
    badReply: 'omg really?? i\'ve been thinking about you too!! when can we talk?',
    badWhy: 'Immediately available. Zero power. Erases all the progress you made moving on.',
    goodReplies: [
      { tone: 'Cool', text: 'oh? what brought that on', why: 'Curious but unbothered. Makes them explain themselves. You hold the power.' },
      { tone: 'Warm', text: 'that\'s sweet. hope you\'re doing well', why: 'Kind but doesn\'t open the door. Classy response if you\'re over it.' },
      { tone: 'Bold', text: 'took you long enough', why: 'Confident, playful, implies you expected it. Strong position.' },
    ],
    tips: [
      'Never reply instantly — wait at least a few hours',
      'Don\'t bring up the breakup or past drama in the first exchange',
      'If it\'s after midnight, they\'re lonely, not in love',
      'Your tone should be warm but not eager. You have a life now.',
      'Don\'t agree to meet up in the first conversation',
    ],
    keywords: ['ex texted me', 'what to say when your ex texts you', 'how to respond to ex', 'ex reached out'],
  },
  {
    slug: 'first-message-dating-app',
    title: 'First Message on a Dating App — What Actually Works',
    metaTitle: 'Best First Messages on Dating Apps That Actually Get Replies',
    metaDescription: 'Tired of getting no replies? These first message examples for Tinder, Hinge, and Bumble actually work — backed by AI analysis of thousands of conversations.',
    heroEmoji: '✨',
    situation: 'You matched. Now you need to send the first message. "Hey" won\'t cut it. Neither will a generic compliment.',
    theirMessage: '(new match — their bio says "take me somewhere I\'ve never been")',
    badReply: 'hey beautiful, how are you doing today? :)',
    badWhy: 'Generic, boring, sounds like a template. They get 50 of these a day.',
    goodReplies: [
      { tone: 'Witty', text: 'does a taco truck at 2am count as somewhere you\'ve never been', why: 'References their bio specifically. Funny. Creates a mini-scene.' },
      { tone: 'Bold', text: 'i know a spot. you free thursday', why: 'Skips small talk entirely. Confident. Implies you have taste.' },
      { tone: 'Playful', text: 'somewhere you\'ve never been? bold. i was just gonna suggest coffee', why: 'Self-aware humor. Light teasing. Shows personality.' },
    ],
    tips: [
      'Always reference something specific from their profile',
      'Questions get more replies than statements on dating apps',
      'Keep it under 15 words. First messages aren\'t essays.',
      'Don\'t compliment their looks — compliment their vibe or interests',
      'Humor > flattery, every time',
    ],
    keywords: ['first message dating app', 'what to say on tinder', 'hinge first message', 'bumble opener', 'best first message on dating app'],
  },
  {
    slug: 'goodnight-text',
    title: 'Goodnight Texts That Actually Hit Different',
    metaTitle: 'Goodnight Texts That Actually Hit — Not Corny, Just Right',
    metaDescription: 'Skip "goodnight 😊". These goodnight texts are smooth, genuine, and make them think about you as they fall asleep.',
    heroEmoji: '🌙',
    situation: 'End of a great conversation. You want to say goodnight without being corny, clingy, or forgettable.',
    theirMessage: 'i should probably sleep soon lol',
    badReply: 'goodnight beautiful!! sweet dreams 😘😘 sleep well!! talk tomorrow!!',
    badWhy: 'Overkill. Too many exclamation marks. Multiple emojis = trying way too hard.',
    goodReplies: [
      { tone: 'Smooth', text: 'go sleep. but you owe me the rest of that story tomorrow', why: 'Casual closer that guarantees the conversation continues.' },
      { tone: 'Warm', text: 'night. this was a good one', why: 'Simple, genuine, memorable. Says a lot with very little.' },
      { tone: 'Flirty', text: 'don\'t dream about me too much', why: 'Playful confidence. Ends on a high note with humor.' },
    ],
    tips: [
      'Less is more. The best goodnight texts are under 8 words.',
      'Reference something from the conversation to make it personal',
      'Plant a seed for tomorrow\'s conversation',
      'Never double-text goodnight. One and done.',
    ],
    keywords: ['goodnight text', 'what to text goodnight', 'cute goodnight messages', 'goodnight text to crush'],
  },
  {
    slug: 'respond-to-hey',
    title: 'How to Reply to "Hey" Without Being Boring',
    metaTitle: 'Someone Texted "Hey" — Here\'s What to Say Back',
    metaDescription: 'Don\'t just say "hey" back. Here are better responses to "hey" texts that actually start a real conversation.',
    heroEmoji: '👋',
    situation: 'They sent "hey" or "hi" or "heyyy". It\'s low effort, but how you respond determines everything.',
    theirMessage: 'heyyy',
    badReply: 'hey! what\'s up?',
    badWhy: 'Mirrors their low effort. Doesn\'t create momentum. Forgettable.',
    goodReplies: [
      { tone: 'Playful', text: 'three y\'s. must be important', why: 'Observational humor. Makes them laugh. Shows you pay attention.' },
      { tone: 'Direct', text: 'what\'s on your mind', why: 'Skips pleasantries. Gets to the real conversation faster.' },
      { tone: 'Flirty', text: 'was wondering when you\'d text me', why: 'Confident. Implies you expected their attention. Charming.' },
    ],
    tips: [
      'The number of y\'s in "heyyy" correlates with interest level (according to internet wisdom)',
      'Don\'t match their energy — elevate it slightly',
      'A response that makes them smile = conversation starter',
      'If they keep sending just "hey" with no follow-up, they\'re bored, not interested',
    ],
    keywords: ['how to reply to hey', 'what to say when someone texts hey', 'response to hey text', 'heyyy meaning'],
  },
  {
    slug: 'she-said-shes-busy',
    title: 'She Said She\'s Busy — What It Means & What to Say',
    metaTitle: '"I\'m Busy" — What It Actually Means and How to Respond',
    metaDescription: 'She said she\'s busy when you asked to hang out. Is she actually busy or not interested? Here\'s how to tell and what to text.',
    heroEmoji: '⏰',
    situation: 'You suggested plans and got hit with "I\'m busy this week" or "I\'ll let you know." Now what?',
    theirMessage: 'i\'d love to but i\'m super busy this week',
    badReply: 'okay no worries! just let me know when you\'re free and we can figure something out maybe!',
    badWhy: 'Over-accommodating. Hands over all the power. "Just let me know" = she never will.',
    goodReplies: [
      { tone: 'Confident', text: 'no rush. hit me when your schedule clears up', why: 'Puts the ball in their court without being passive-aggressive. Shows you have a life.' },
      { tone: 'Smooth', text: 'busy is good. means you\'re interesting', why: 'Reframes it positively. Compliments without simping. Memorable.' },
      { tone: 'Direct', text: 'what about next tuesday', why: 'Offers a specific alternative. Interested people will find time.' },
    ],
    tips: [
      'If she doesn\'t suggest an alternative day, she\'s probably not interested',
      '"I\'m busy" + counter-offer = actually busy. "I\'m busy" alone = soft rejection.',
      'Never ask more than twice. If she doesn\'t make effort, move on.',
      'Don\'t keep texting normally after being turned down. Let the space breathe.',
    ],
    keywords: ['she said she\'s busy', 'what to say when she says she\'s busy', 'she cancelled plans', 'girl says she\'s busy'],
  },
  {
    slug: 'how-to-flirt-over-text',
    title: 'How to Flirt Over Text Without Being Weird',
    metaTitle: 'How to Flirt Over Text — Without Coming Across as Creepy',
    metaDescription: 'Flirting over text is an art. Here\'s how to be playful, confident, and attractive without crossing the line into cringe territory.',
    heroEmoji: '😏',
    situation: 'You want to show interest and create romantic tension, but you don\'t want to come across as creepy or try-hard.',
    theirMessage: 'that was actually really fun tonight',
    badReply: 'yeah it was!! you\'re so amazing and beautiful. i had the best time ever honestly you\'re incredible',
    badWhy: 'Way too much, way too fast. Overwhelming compliments kill attraction. Less is more.',
    goodReplies: [
      { tone: 'Teasing', text: 'don\'t get used to it. i\'m not always this fun', why: 'Self-deprecating humor + challenge. Creates playful tension.' },
      { tone: 'Smooth', text: 'you made it easy', why: 'Short compliment that gives credit to them. Confident, not desperate.' },
      { tone: 'Forward', text: 'next time\'s on me then', why: 'Assumes a next time. Confident. Plants the seed for another date.' },
    ],
    tips: [
      'Tease > compliment. Playful teasing creates tension that compliments don\'t.',
      'Never send multiple compliments in a row',
      'Use statements instead of questions — "we should do that again" not "would you want to do that again?"',
      'If they flirt back, escalate slightly. If they don\'t, pull back. Read the energy.',
      'Confidence = saying less, not more',
    ],
    keywords: ['how to flirt over text', 'flirty texts', 'how to be flirty over text', 'texting tips flirting'],
  },
  {
    slug: 'revive-dead-conversation',
    title: 'How to Revive a Dead Conversation Over Text',
    metaTitle: 'Dead Conversation? Here\'s How to Bring It Back to Life',
    metaDescription: 'The conversation fizzled out days ago. Here\'s how to text them again without looking desperate — smooth moves to restart any convo.',
    heroEmoji: '🔄',
    situation: 'You were talking regularly, then the conversation just... stopped. It\'s been 3-7 days of silence.',
    theirMessage: '(last message was 5 days ago)',
    badReply: 'hey stranger! where\'d you disappear to? lol miss talking to you',
    badWhy: '"Hey stranger" is the most overused and cringe revival text. "Miss talking to you" = needy.',
    goodReplies: [
      { tone: 'Callback', text: 'update: that restaurant was actually fire', why: 'References a past conversation topic. Natural. Doesn\'t acknowledge the gap.' },
      { tone: 'Value-add', text: 'this reminded me of you', why: 'Send with a meme, article, or photo. Shows you thought of them. Low pressure.' },
      { tone: 'Direct', text: 'alright i need your opinion on something', why: 'Creates curiosity. Gives them a reason to reply. Engaging opener.' },
    ],
    tips: [
      'Never acknowledge the silence gap — act like it\'s normal',
      'Lead with value (meme, question, callback) not with "hey"',
      'One attempt only. If they don\'t reply to your revival text, it\'s over.',
      'The best revivals reference something you previously talked about',
      'Timing matters — send it during evening hours when they\'re likely free',
    ],
    keywords: ['how to revive a dead conversation', 'text after no contact', 'restart conversation over text', 'how to text someone after a long time'],
  },
  {
    slug: 'double-texting',
    title: 'When to Double Text (And When Not To)',
    metaTitle: 'Should You Double Text? The Rules of Double Texting',
    metaDescription: 'Is it okay to double text? Here\'s when double texting is perfectly fine, when it\'s desperate, and what to say if you do it.',
    heroEmoji: '📲',
    situation: 'You sent a message, got no reply. Your finger is hovering over the keyboard. Should you send another one?',
    theirMessage: '(no reply to your last message)',
    badReply: '?? \n hey \n hello?? \n are you ignoring me',
    badWhy: 'Multiple pings = desperation alarm. "Are you ignoring me" kills any chance of a reply.',
    goodReplies: [
      { tone: 'Natural', text: 'oh also — [new topic/link]', why: 'Organic reason to text again. Doesn\'t reference the silence.' },
      { tone: 'Funny', text: 'i\'m choosing to believe you\'re skydiving rn', why: 'Humor breaks the tension. Light-hearted acknowledgment without pressure.' },
      { tone: 'Direct', text: 'plans changed for saturday. you in or out', why: 'Time-sensitive context makes double texting logical, not desperate.' },
    ],
    tips: [
      'Wait at least 24 hours before double texting',
      'Your second text should be a new topic, not a follow-up to the ignored one',
      'Double texting is fine if you have a genuine reason (plans, something funny, news)',
      'If you double text and still get no reply — do NOT triple text',
      'Confident people double text sometimes. Desperate people do it constantly.',
    ],
    keywords: ['double texting', 'is it okay to double text', 'should i double text', 'double text rules'],
  },
  {
    slug: 'one-word-replies',
    title: 'Getting One-Word Replies? Here\'s the Move',
    metaTitle: 'One-Word Replies — What They Mean and How to Respond',
    metaDescription: 'If they keep replying with "ok", "cool", or "lol", here\'s what it means and the best way to handle it without looking desperate.',
    heroEmoji: '😐',
    situation: 'Every message you send gets a "ok", "cool", "nice", or "lol" back. You\'re doing all the work.',
    theirMessage: 'cool',
    badReply: 'so anyway how was your weekend? did you do anything fun? i went hiking and it was really nice',
    badWhy: 'Overcompensating for their lack of effort. Paragraph replies to one word = chasing.',
    goodReplies: [
      { tone: 'Mirror', text: 'cool', why: 'Match their energy. If they want to talk, they\'ll make effort.' },
      { tone: 'Pivot', text: 'come to [event] on friday. bring your energy', why: 'Stop texting, start doing. Some people just don\'t text well.' },
      { tone: 'Exit', text: '✌️', why: 'Sometimes the best reply is the exit. Protect your time and energy.' },
    ],
    tips: [
      'One-word replies = they\'re either not interested or a bad texter',
      'Stop asking questions. Make statements or just match their energy.',
      'If you\'ve been carrying the conversation for 10+ messages, stop.',
      'The person who cares less has the power. Don\'t be the one over-investing.',
    ],
    keywords: ['one word replies', 'she replies with one word', 'dry replies', 'what to do when someone gives one word answers'],
  },
  {
    slug: 'what-to-say-after-first-date',
    title: 'What to Text After a First Date',
    metaTitle: 'What to Text After a First Date — Timing, Tone & Examples',
    metaDescription: 'The first date went well. Now what? Here\'s exactly when and what to text after a first date to lock in the second one.',
    heroEmoji: '🍷',
    situation: 'The date just ended (or ended last night). You want to follow up without being too eager or too cold.',
    theirMessage: '(date ended 2 hours ago)',
    badReply: 'i had SUCH an amazing time tonight!! you\'re literally so perfect. when can i see you again??',
    badWhy: 'Too much, too fast. Multiple exclamation marks + "perfect" + immediately asking for another date = desperate.',
    goodReplies: [
      { tone: 'Smooth', text: 'got home safe. that was fun', why: 'Simple, warm, leaves the door open. "Fun" not "amazing" — understated confidence.' },
      { tone: 'Callback', text: 'still can\'t believe you\'ve never tried [thing from date]', why: 'References a specific moment. Shows you paid attention. Starts natural conversation.' },
      { tone: 'Forward', text: 'next time i\'m picking the spot', why: 'Assumes a next time without asking permission. Confident. Plants the seed.' },
    ],
    tips: [
      'Text within 2-4 hours after the date. Same night is fine, next morning is fine too.',
      'Keep the first text short. Save the longer conversation for the second date.',
      'Reference a specific moment from the date — it shows genuine interest',
      'Don\'t ask "when can I see you again" — say "we should do [activity] next time"',
      'If they don\'t text first, don\'t read into it. Many people wait for the other person.',
    ],
    keywords: ['what to text after first date', 'after first date text', 'first date follow up text', 'text after date'],
  },
  {
    slug: 'he-hasnt-texted-back',
    title: 'He Hasn\'t Texted Back — What to Do',
    metaTitle: 'He Hasn\'t Texted Back? Don\'t Spiral. Do This Instead.',
    metaDescription: 'It\'s been hours (or days) and he hasn\'t texted back. Before you overthink it, here\'s what\'s actually going on and what to do.',
    heroEmoji: '🤔',
    situation: 'You texted him and he hasn\'t replied. You\'re staring at your phone, checking if iMessage shows "delivered" vs "read."',
    theirMessage: '(no reply — it\'s been 8 hours)',
    badReply: 'hey just checking if you got my message? \n sorry if i said something wrong \n are we okay?',
    badWhy: 'Apologizing when nothing happened. Triple texting. Assuming the worst. This pushes people away.',
    goodReplies: [
      { tone: 'Unbothered', text: '(don\'t text anything yet)', why: 'Sometimes the best reply is no reply. Give it 24 hours minimum.' },
      { tone: 'Natural', text: '[send a funny meme or reel]', why: 'After 24h, a meme is the lowest-pressure way to re-engage. No words needed.' },
      { tone: 'Confident', text: 'your silence is very dramatic', why: 'After 48h+, humor works. Acknowledges it without being needy.' },
    ],
    tips: [
      'People have lives. 8 hours of no reply is normal, not a crisis.',
      'Never send "did I do something wrong" — it puts you in the wrong even when you\'re not',
      'The more you text while being ignored, the less attractive you become',
      'If he consistently takes days to reply, that IS his answer',
      'Put your phone down and do something else. Seriously.',
    ],
    keywords: ['he hasn\'t texted back', 'why isn\'t he texting me back', 'guy not responding to texts', 'he stopped texting'],
  },
  {
    slug: 'lol-response',
    title: 'They Replied "lol" — Now What?',
    metaTitle: 'They Said "lol" — Is the Conversation Dead? Here\'s What to Do',
    metaDescription: 'When someone replies with just "lol", the conversation is on life support. Here\'s how to either revive it or gracefully move on.',
    heroEmoji: '😂',
    situation: 'You said something you thought was engaging and all you got back was "lol". The dreaded conversation-killer.',
    theirMessage: 'lol',
    badReply: 'haha yeah so anyway what are you doing this weekend? any plans? want to hang out?',
    badWhy: 'Immediately trying to restart after a dead-end. Asking 3 questions after getting "lol" = desperate.',
    goodReplies: [
      { tone: 'Power Move', text: '(leave it on read)', why: 'If "lol" is all they give, silence is your best response. Protect your energy.' },
      { tone: 'Topic Shift', text: 'alright new topic. [something interesting]', why: 'Directly pivots without pretending "lol" was a real response.' },
      { tone: 'Mirror', text: 'lol', why: 'Matching their energy. Ball is now in their court to make actual effort.' },
    ],
    tips: [
      '"lol" by itself usually means "I don\'t know what to say but I\'m not uninterested"',
      'Don\'t try to save a conversation someone isn\'t helping you carry',
      'If their last 3 messages were "lol", "haha", and "yeah" — stop texting',
      'A person who wants to talk to you will give you more than "lol"',
    ],
    keywords: ['how to reply to lol', 'she said lol', 'lol text response', 'conversation dying text'],
  },
];

export function getGuideBySlug(slug: string): SeoGuide | undefined {
  return SEO_GUIDES.find(g => g.slug === slug);
}
